name: 'PR Title Validation'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        run: |
          title=$(jq -r '.pull_request.title' $GITHUB_EVENT_PATH)
          regex='^(feat|fix|chore|docs|test|style|refactor|perf|build|ci|revert)(\([^)]+\))?: .{1,}$'
          if [[ "$title" =~ $regex ]]; then
            echo "PR 제목 유효성을 통과하였습니다."
          else
            echo "PR 제목이 잘못되었습니다. 예시) feat: 제목"
            exit 1
          fi
